


// src/redux/actionTypes.js
export const GET_USERS = 'GET_USERS';
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';
export const GET_USERS_FAILURE = 'GET_USERS_FAILURE';

export const GET_PRODUCTS = 'GET_PRODUCTS';
export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS';
export const GET_PRODUCTS_FAILURE = 'GET_PRODUCTS_FAILURE';

export const GET_CATEGORIES_REQUEST = 'GET_CATEGORIES_REQUEST';
export const GET_CATEGORIES_SUCCESS = 'GET_CATEGORIES_SUCCESS';
export const GET_CATEGORIES_FAILURE = 'GET_CATEGORIES_FAILURE';

export const GET_BLOGPOSTS_REQUEST = 'GET_BLOGPOSTS_REQUEST';
export const GET_BLOGPOSTS_SUCCESS = 'GET_BLOGPOSTS_SUCCESS';
export const GET_BLOGPOSTS_FAILURE = 'GET_BLOGPOSTS_FAILURE';

export const GET_ORDERS_REQUEST = 'GET_ORDERS_REQUEST';
export const GET_ORDERS_SUCCESS = 'GET_ORDERS_SUCCESS';
export const GET_ORDERS_FAILURE = 'GET_ORDERS_FAILURE';

export const GET_ORDER_DETAIL_REQUEST = 'GET_ORDER_DETAIL_REQUEST';
export const GET_ORDER_DETAIL_SUCCESS = 'GET_ORDER_DETAIL_SUCCESS';
export const GET_ORDER_DETAIL_FAILURE = 'GET_ORDER_DETAIL_FAILURE';

export const GET_BLOGS_REQUEST = 'GET_BLOGS_REQUEST';
export const GET_BLOGS_SUCCESS = 'GET_BLOGS_SUCCESS';
export const GET_BLOGS_FAILURE = 'GET_BLOGS_FAILURE';

export const GET_BLOG_NAME_REQUEST = 'GET_BLOG_NAME_REQUEST';
export const GET_BLOG_NAME_SUCCESS = 'GET_BLOG_NAME_SUCCESS';
export const GET_BLOG_NAME_FAILURE = 'GET_BLOG_NAME_FAILURE';

export const GET_COUPONS_REQUEST = 'GET_COUPONS_REQUEST';
export const GET_COUPONS_SUCCESS = 'GET_COUPONS_SUCCESS';
export const GET_COUPONS_FAILURE = 'GET_COUPONS_FAILURE';

export const GET_COUPON_CODE_REQUEST = 'GET_COUPON_CODE_REQUEST';
export const GET_COUPON_CODE_SUCCESS = 'GET_COUPON_CODE_SUCCESS';
export const GET_COUPON_CODE_FAILURE = 'GET_COUPON_CODE_FAILURE';